---
language: go

go:
  - 1.6

sudo: false

env:
  global:
    - secure: ALco8w6B/di5jwPMSY/IWYRlTq7cPqoo+GSHYZfqoLZfcya7TsuQYQuWEAMySXRy6Kd6CliI7qZBhwB4myCCFlMeIYJhURLEunIUoEOxNzTFzPw+qRN5Bx7gE4C8LvXyeQ6ykOkKsV1T3O0nvPtPFfSRcYLrBpNcHFmZqZcY0kwdlvikPhmpMSnghYz0TtJID/UFMJx/23XjKta0ksCnPaFPmB2ioZXhLX7t+Vd/d+1TEwyHLlG+8NoFKUhzLn+lhDVIrpA0WV1CFnSyevKAt5zzx2N92WKYBRZ1wZM0BEB/uu7Gm9tNzXCQE2r+zxlgnCTWTImhqaS6KEjYKn5Sw13onj4R0vRZTd8jofq2dKKAVOlWwuGoTGthDjjUQFAfT5fMf0kikHQ05fzXNbsCKnsd6DAMTSC7lbSxCQcagx3pLXHXECAj8ml3BPnyi/b88APMDO+XBnsw2Z0h2kbEi68yIlo7N0N+DK16vUwgNUUeaV5V4JYdoPwlcWga9pRKzeBJQJz/BBdfLlV8+IWYxm2pQe8jMJbmLNTe4plqp7T2IJnzmOBFgqWf4hGipW4x8+N+gszF7eAMkue5lUY1PZWVGlwZaL4hIcgfTwrk+zmYOfUiK+Im0uAiEtdsJE4kfo/GfzLOxTfV81L1E/i7zlrLt+pJMhbKaN3WoyMFg5Y=
    - secure: VpL67YhVd313+xWZaVMKErt1qjB4f6QIubGg1LuJHLGuhX4tyrBYMCSCY3IRaTLhwvS9Kte6t1DDAc4jYFjzucNSjHKudwI5DMkTSl5zZJJb1AKq6NVIla53BWN3+7+9j5nb2orKHbnJm8mMnPtAISg7V9GM27gQpEQOBhDwtfSBTkZ5XcnHti15owrSxl2Rn76eMgijm3IdSOh0432rATIEzktPfC3IegfVT9EaC5cpnLEwCHJ73U+zs9tam9GL5mVH3VW5xm4qGAA4V61D/G6lVKhbsfj6XRYuat/RHSYubi6bdHklD9tj5Bkl3xCsSeZAhXjqb7Oy+QaKLv4t+0MzUPFHhcd3yUUmNbt7Slzo4IvNyclsorC7Oq/iLlGDLI2xWCTuCeglPAfuExGxgUBfhf065hmQx9WarzmcEAqHe3McduZZQCAys04svZ0iCVr2gWVTO3dsiac9FNI8DCXp2Mg8EgUNgXrchn8UuYdoR/oePSK9/FGAIEPyFkNQ7oC0mCCnpSXkHX4BosoLCQJhTykEb4XCcCdvvZjhxBcAfMjoKU5UN7SZcJIit8SD3+cGBpTFfU7gFPytZcTykq8x4HrYXQRXAaR4pirgAGOtcsGfSoE59GKlevO2Rrj3MwEbFoqLiyqnU6I4EhFIYk4/kfxTAnm5llrR9vlKQmg=
    - secure: eZM8n/KJcX/zDzhDf3HraRQIKHGH011R9KmCn5qbMhkCUq25HRpRhlPpyI9VChJ4bv2+YEEKmPDlmCFW4Gw1uprpazBRDJiJDu1Ec0YK+JOGBdKtQ5UF1qw92+riylS66/RHceF5lrPsPtW5oOocZ6aW0IaKQSSFNVlA4IwkuW0oZ1t472zOveKBoDkwcjjItURn7Ur93ZC/Iyzt8I5qRw49fuIxbUxIP6PMOiz8/gmxsE0QUCGq2XQSbDj3gXiZwIpbHh3+3NLe5GOGercWkt50koV+tZeOyq3Rl5kTyoxx8FfbVXcsPfswOh+GRZC526Kcbl5b7NdiulxOvt9NiAnwqHnTTUFHwec3SOY01POWb1LK7hAAihQPsT30DVttKf16lTEVLr6Wg99+2dMKr63qAXTIKgxFgcIK0DVDq4b116dak2sooYDKQFjaHZX7JDb4tDj4+yot+916vx5GGIsOFj72bpINVzEjieuk6sqL7hTdJjxI84mC1RGABYK8urSB6KCXynM0BjDHeqaMFmKQI8LajzDk+wBJk//eOVLITZCoXwQXtqsAwHDYr8sdMF1cg7GQil1UvqW9E4YZrskKwOBANRF3mlri5OkLhalCQtngd8MyzGZ54hVmY/UFPa2/OS34RpxXGcCM3dyJX+BHXM3jy+w+/EnpbvFXsJ4=

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  - provider: s3
    access_key_id:
      secure: FaQRlKFYMiKinmrOVq7XptGE3t+Qxs8LtyxMRBHuxAEiSXjhKQwrg6ysTddCZdB2Q8QB6LnnC2ji1kOCnNT3ANcf9mtmCWKvPGp61mBCtyXI+/JvgRNL4MwcLqFe/fpkjxne5hb/nMu4vUuRicdlchH8rbek/o1FVsay2qgt81M2+RbyoqUHqvX4/a2CkU30VoP5tpgI7wdZfRbpcgHWZEq+EQD3K/o2ndNucw9StZyGbDvgnR4k9LK3AZIxyl5sMVMeD3XwplhT5XKRdNa0iYtSKYpzIRLNragaRm3jZh9brFKJ02bUOflutPXsl57yZF4hdJrBYMsPlEAqhX6bw5uhWTQ3/P01WHuU2vY9a7wEh2CH+UxygpF2/vFetoXDCXxHVBxCKlP5CazsRgH79nBjoGZX7jiw6ys9qyw0bsLesUYIh5w00EbBsAL9qqyeFEGMBesRU+JHFebGHw+WJEHixNX3YkdxYZTmTeRsnby0zUgLYHhlP+IgxECUka7v+fFphP5D/swWvPeY01X+6fyyZvg0KAYrlIAeiNeLp0C3eYYTbRyTmLiRcTSljv5PmKgC456ifztT8pYdG+cgBNdFFNBeGCN9puhzq/K1qxlSaVuSxaBiMCsueCqh1/ZwV4sDy/BcqzxVErmM7TQh7mBDxVORZw5COBOGx6yZjmQ=
    secret_access_key:
      secure: PYYJBW5QniMAXYLC1a0B0/aMgD+cpn0SCgTpugfhYbyhh3p5/45IXX/xkFgfsOeccip/qhl0cqLlaTFGIh5Kr4I0VL3HJbYS20ZsyxYNvrvHNkPLeSc/zgbb0HgIOCU/q8OgGDIqSML/H+7E7F25qLvBKTXjBv8CYA1Zn/Sps2+bIMIr2O4Iu1dpaz07jpvtOJrotMuvBHiXM8klk2p7+y6ZCS0rgBoGcTEcEeQ/vrFCFzVdzY9XwaIZRv1+NaAFIy3Sa+TyXMruaJoQLp1eq+Mq6JRI7AsHxbKJzhk9+ur1DkzTiVoWyf55NofxCeMEgLe9uh+BkI1vgfxZBkJgjzytnx8BaWbfLZ9tx2Lwqhg2DpyY2RvVrJneccoFC6S56yztMcMm0UaMzNygxLlmT1HqOf2UUJhD8lTnBkoLl0LkA5qYNmt4IXXiurcq74Lxn58IIoLFsi5YtjUxEG7ySf9bHGdpm4Cg4CJ3OMG2ZwzzHB6MDKPs5OeAdjQ3GYpbT+ZvxkSt1eO/xaOHnEfSwN2/rXRhVtJvvCgGUjUPYTRW5ZXRq0ATXZrRZsA21ocAjWGkoJ1PahFNUbcIUPl2B1jyOD1wFYSUibEbFZ84nEDUubuHXLOmMCJjifVTqkA6PFZahVgQfb9FMC7Ng7U6mYsImGGrjP7H/A8qypkjH+8=
    bucket:
      secure: ij5mKaauiqZ6CzdyfVLgffKsE2uW1uQ/Ipb3HkXSOhQ1J42UVTC2qCip9BdVgrUqWyf3W4xs9U3J/odhSXvlCdQh4mGkbIOU3qe5LS9OsmgpKPekQBVl77kd2o6rM0Yxpa8qM/ac0I10RrHFaNv5OO0mY4uxW0p8ampOM7eGyhTd/uKazGkc/8CVFrsdaZ1mHc/7o526EThyze3/e/IL0T5n5nJDf0JDzbf/9MtcyYLS+12GYLwibY3GZ86mGmNQrr4jKfGycLypHpqtJuQBvOZ91eekALSKb+9G2h6D1ArnpDzkW5RNGDj/tKzQGZMfzdWZ00VJUB52cxGtb+6q/5K7L1DWgD1SeJwwy03qXRNfS+m70gObjkcf942tu+06NTPLlihjdMaAv0k9XX1Zax4QvSOvLO47MPyn06dLk6yw+igDBV212ArK7xjPHiqH+zVawEnCBi+kRTTFwIUzZhxtS5uz9D5Z3c8VEZeJNQEqP6ltxNoQFBk/jOrNZi7rakRbg/B+LBoxY9ELqVAyGx0HfNcYBFALL3SjO9pG+vQN7Y8tgYLstItn+KUN3yDn1d8XATP43gYVJMC12WWbCrZ5Ev4jg1ReKV5Xdp9ekQ8IJfiZZN9TGshu6ZUx5JjwvZ5NdN7T1iCuMMCFDBotAX2g8OgMkF3H5i5thalP+Kg=
    region: eu-west-1
    local_dir: public
    skip_cleanup: true

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths /

